# Generated by Django 4.2.2 on 2023-06-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rgct', models.BigIntegerField()),
                ('position', models.IntegerField()),
                ('abo', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('panel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rgct', models.BigIntegerField()),
                ('position', models.IntegerField()),
                ('abo', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('panel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rgct', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('opo', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('death_cause', models.TextField()),
                ('cr_in', models.CharField(max_length=100)),
                ('cr_out', models.CharField(max_length=100)),
                ('hypertension', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('hbsag', models.BooleanField()),
                ('anti_hcv', models.BooleanField()),
                ('avch_death', models.BooleanField()),
                ('chagas', models.BooleanField()),
                ('anti_hbs', models.BooleanField()),
                ('hltv', models.BooleanField()),
                ('vdrl', models.BooleanField()),
                ('anti_hbc', models.BooleanField()),
                ('hiv', models.BooleanField()),
                ('toxoplasmosis', models.BooleanField()),
                ('age_50_60', models.BooleanField()),
                ('cr_in_greater_than_15', models.BooleanField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organreport')),
            ],
        ),
    ]
