# Generated by Django 4.2.2 on 2023-06-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacient',
            new_name='Patient',
        ),
    ]
