# Generated by Django 4.2.2 on 2023-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='abo',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='receiver',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='receiver',
            name='panel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='rgct',
            field=models.BigIntegerField(default=0),
        ),
    ]
