# Generated by Django 4.2.2 on 2023-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receiver_abo_receiver_age_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donator',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='donator',
            name='death_cause',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donator',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='donator',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='donator',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donator',
            name='opo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donator',
            name='report',
            field=models.FileField(blank=True, default='', upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='donator',
            name='rgct',
            field=models.BigIntegerField(default=0),
        ),
    ]
