# Generated by Django 4.2.2 on 2023-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donator_age_donator_date_donator_death_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
