# Generated by Django 4.2.2 on 2023-06-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donator_rgct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='report',
        ),
    ]
