# Generated by Django 4.2.2 on 2023-07-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donator_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='date',
        ),
    ]
