# Generated by Django 4.2.2 on 2023-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
