# Generated by Django 4.2.2 on 2023-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_donator_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
