# Generated by Django 4.2.2 on 2023-07-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_donator_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='opo',
        ),
        migrations.AddField(
            model_name='donator',
            name='abo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='abo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2),
        ),
    ]
