# Generated by Django 4.2.2 on 2023-07-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_acceptance_user_firstaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
