# Generated by Django 3.2.12 on 2023-07-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_acceptance_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstAccess',
            new_name='PasswordChangeRequest',
        ),
    ]
