# Generated by Django 4.2.2 on 2023-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_firstaccess_passwordchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='decision',
            field=models.CharField(choices=[('A', 'Aceito'), ('R', 'Rejeitado')], default='A', max_length=2),
        ),
    ]
