# Generated by Django 4.2.2 on 2023-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_acceptance_compatibility_alter_acceptance_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='compatibility',
            field=models.BooleanField(default=True),
        ),
    ]
