# Generated by Django 4.2.2 on 2023-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_acceptance_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donator',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donator',
            name='rgct',
            field=models.CharField(max_length=100),
        ),
    ]
