# Generated by Django 4.2.2 on 2023-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_donator_date_alter_donator_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donator',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='rgct',
            field=models.CharField(max_length=100),
        ),
    ]
