# Generated by Django 4.2.2 on 2023-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_donator_date_alter_donator_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], default='m', max_length=1),
        ),
    ]
